### ISSUE TITLE
UnboundLocalError in ipython

### ISSUE THREAD

**Issue by smartalecH** [NanoComp/meep#1164]
There's a bug when the user specifies a simulation run function (e.g. `stop_when_fields_decayed`) *and* iPython is in the current python environment. The issue is related to the Jupyter notebook progress bar update #1078.

Here's a simple test script:

```python
import numpy as np
import meep as mp
from matplotlib import pyplot as plt

sx = 8
sy = 6
cell = mp.Vector3(sx, sy, 0)
geometry = [mp.Block(center=mp.Vector3(), size=mp.Vector3(mp.inf,0.5,0), material=mp.Medium(epsilon=12))]

fcen = 0.15
df = 0.1
sources = [mp.Source(mp.GaussianSource(fcen, fwidth=df), component=mp.Ez,
                        center=mp.Vector3(1 + (-0.5 * sx), 0), size=mp.Vector3(0, 2))]

pml_layers = [mp.PML(2.0)]
resolution = 10
nfreq = 100

sim = mp.Simulation(cell_size=cell,
                            boundary_layers=pml_layers,
                            geometry=geometry,
                            sources=sources,
                            resolution=resolution)
sim.run(until=mp.stop_when_fields_decayed(50, mp.Ez, mp.Vector3(), 1e-6))
```

Which throws the following error:

```
Traceback (most recent call last):
  File "test_converge.py", line 51, in <module>
    sim.run(until=mp.stop_when_fields_decayed(50, mp.Ez, mp.Vector3(), 1e-6))
  File "/$$meep_python_filepath$$/simulation.py", line 2249, in run
    self._run_until(until, step_funcs)
  File "/$$meep_python_filepath$$/simulation.py", line 1498, in _run_until
    self.progress.value = t0 + stop_time
UnboundLocalError: local variable 't0' referenced before assignment
```

As the error indicates, `t0` is not properly defined:
https://github.com/NanoComp/meep/blob/5e48aa2ad014942881239ade7988acc162e02199/python/simulation.py#L1497-L1499

Travis probably didn't catch this since iPython isn't part of the [yaml file build instructions](https://github.com/NanoComp/meep/blob/master/.travis.yml).

**Comment by smartalecH** [comment]
Note: `stop_time` is not properly initialized/defined either.
