### ISSUE TITLE
quick problem with swig and mpb?

### ISSUE THREAD

**Issue by acerjan** [NanoComp/meep#1261]
I was trying to run mpb through python this morning using the latest version from github, and received the error:
Traceback (most recent call last):
  File "sqr_sphere_env.py", line 30, in <module>
    from meep import mpb
  File "/home/alex/local/lib/python3.6/site-packages/meep/mpb/__init__.py", line 20
    from . import _mpb
       ^
IndentationError: expected an indented block

A few lines required indentation in __init__.py, but after fixing them, the code ran as expected. However, as I can see that this file is automatically generated, this is clearly not a permanent fix. Or do I need to update my installation of swig?

**Comment by stevengj** [comment]
What does `swig -version` print for you?

**Comment by acerjan** [comment]
SWIG Version 3.0.12

Compiled with g++ [x86_64-pc-linux-gnu]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information
