### ISSUE TITLE
error in doc/generate_py_api.py related to backward compatibility of ast module

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#1358]
Following #1348 which added the `ast` module as a dependency, running `python3.5 doc/generate_py_api.py` from the source tree with no changes produces the following error:

```py
$ python3.5 doc/generate_py_api.py
Using MPI version 3.1, 1 processes
Traceback (most recent call last):
  File "doc/generate_py_api.py", line 422, in <module>
    main(sys.argv[1:])
  File "doc/generate_py_api.py", line 416, in main
    doc_items = generate_docs(items)
  File "doc/generate_py_api.py", line 383, in generate_docs
    doc = item.create_markdown()
  File "doc/generate_py_api.py", line 315, in create_markdown
    docs[class_name+'[all-methods]'] = class_doc + '\n' + self.create_method_markdown(False)
  File "doc/generate_py_api.py", line 338, in create_method_markdown
    doc = item.create_markdown()
  File "doc/generate_py_api.py", line 272, in create_markdown
    parameters = self.get_parameters(4 + len(method_name) + 1)
  File "doc/generate_py_api.py", line 109, in get_parameters
    parameters = self.get_parameters_from_ast()
  File "doc/generate_py_api.py", line 171, in get_parameters_from_ast
    default = self.transform_node(name, node)
  File "doc/generate_py_api.py", line 187, in transform_node
    elif isinstance(node, (ast.Constant, ast.NameConstant)):
AttributeError: module 'ast' has no attribute 'Constant'
```
This is because the class [`ast.Constant`](https://docs.python.org/3/library/ast.html#node-classes) was used for all constants only starting with version 3.8. Unfortunately, this means it is not backwards compatible with older versions of Python3.

**Comment by RobinD42** [comment]
It appears to have been added in Python3.6 (and I tested with Python 3.6 through 3.8 last week):

```
>  python3.6
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 03:02:14)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ast
>>> ast.Constant
<class '_ast.Constant'>
>>>
```

I'll check if there is an easy way to work around this for Python 3.5, but I think this probably should be a low priority since things will work from 3.6 onward, and 3.5 reached "end of support" from Python.org this month.
