### ISSUE TITLE
multilevel_atom.py test fails when compiling with --disable-portable-binary

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#1426]
When building from source using the `--disable-portable-binary` compiler flag (described in #1423), all the tests in the `make check` suite pass except for `multilevel_atom.py`:

```
======================================================================
FAIL: test_multilevel_atom (__main__.TestMultiLevelAtom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/multilevel_atom.py", line 66, in test_multilevel_atom
    sim.run(mp.at_end(check_field), until=7000)
  File "/usr/local/lib/python3.5/site-packages/meep/simulation.py", line 3634, in run
    self._run_until(until, step_funcs)
  File "/usr/local/lib/python3.5/site-packages/meep/simulation.py", line 2195, in _run_until
    _eval_step_func(self, func, 'finish')
  File "/usr/local/lib/python3.5/site-packages/meep/simulation.py", line 4016, in _eval_step_func
    func(sim, todo)
  File "/usr/local/lib/python3.5/site-packages/meep/simulation.py", line 4087, in _end
    _eval_step_func(sim, func, 'step')
  File "/usr/local/lib/python3.5/site-packages/meep/simulation.py", line 4014, in _eval_step_func
    func(sim)
  File "tests/multilevel_atom.py", line 62, in check_field
    self.assertAlmostEqual(fp, -2.7110969214986387)
AssertionError: -0.04452311652305546 != -2.7110969214986387 within 7 places
```

As shown in the output above, the error in the actual vs. expected value is significantly larger than floating-point rounding errors, etc. 

This test failure has been verified on two separate machines.

cc @acerjan

**Comment by stevengj** [comment]
Weird.  What version of gcc are you using?

**Comment by oskooi** [comment]
I tested with gcc `5.4.0` on Ubuntu 16.04 and `7.5.0` on Ubuntu 18.04 with the following flag:
```
CXXFLAGS='-O3 -fstrict-aliasing -march=native -Wall -W -fopenmp'
```
