### ISSUE TITLE
bending-loss tutorial in cylindrical coordinates

### ISSUE THREAD

**Issue by stevengj** [NanoComp/meep#1476]
In principle, we can use a cylindrical simulation to compute the rate of bending loss from curved waveguide; it might be nice to show this in a tutorial.

In particular, suppose you have a straight waveguide, with a mode at (k₀,ω₀), and you want to look at its rate of bending loss for a bend radius R.  Then:

1. Make a cylindrical computational cell for r = R-D/2 to R+D/2, i.e. radial width D centered on R, with D/2 < R, so that it does *not* include the r=0 origin.   Have PML on *all* sides, including the inner radius.  Put the waveguide at the center of the cell (centered on r=R).

2. Do the Meep run with m=k₀R — note, that if k₀ is given as in MPB without the 2π factor, you should use m=2πk₀R.   (IIRC correctly, Meep does *not* require `m` to be an integer if the computational cell does not include the origin.)

3. Treat it like a resonant-mode calculation: put in a point source, hit it with a pulse, and use harminv to get the complex frequency ω+iγ.   You should find a mode at ω ≈ ω₀ corresponding to your straight-waveguide mode.  Then the spatial decay rate (imaginary part of k) is γ/vg where vg is the group velocity (again you should be careful of 2π factors).

(Note that this does *not* give the transition loss at the transition between the straight waveguide and the bend.)

**Comment by oskooi** [comment]
I have set up the simulation in cylindrical coordinates to compute the bending loss of a [SOI strip waveguide](http://www.simpetus.com/projects.html#mpb_waveguide) at a wavelength of 1.55 μm following the outline above. The propagation wavevector and group velocity of the mode are computed separately in MPB.

The problem, however, is that the loss due to the bend is quite small even for a relatively small radius of curvature: ~2e-05 at a radius of 1.0 μm. Verifying such a tiny quantity using the full 3d simulation is challenging because it would require: (1) a large resolution and (2) an even smaller transition loss.

Is it possible to verify the transition loss *without* performing the 3d simulation?

```py
import meep as mp
import numpy as np

import argparse
parser = argparse.ArgumentParser()
parser.add_argument('-res',
                    type=int,
                    default=20,
                    help='resolution (default: 20 pixels/um)')
parser.add_argument('-Rb',
                    type=float,
                    default=1.5,
                    help='radius of curvature of bend (default: 1.5 um)')
args = parser.parse_args()

resolution = args.res

w = 0.50 # width                                                                                                                                                                                      
h = 0.22 # height                                                                                                                                                                                     
Rb = args.Rb  # radius of curvature of bend                                                                                                                                                           

Si = mp.Medium(index=3.45)
SiO2 = mp.Medium(index=1.45)

dsub = 2.0
dair = 1.0
dpml = 1.0

sr = Rb+w/2+dair+dpml
sz = dpml+dsub+h+dair+dpml

cell_size = mp.Vector3(sr,0,sz)

pml_layers = [mp.PML(thickness=dpml)]

geometry = [mp.Block(center=mp.Vector3(Rb,0,-0.5*sz+dpml+dsub+0.5*h),
                     size=mp.Vector3(w,0,h),
                     material=Si),
            mp.Block(center=mp.Vector3(0.5*sr,0,-0.5*sz+0.5*(dpml+dsub)),
                     size=mp.Vector3(sr,0,dpml+dsub),
                     material=SiO2)]

fcen = 1/1.55
df = 0.05*fcen
sources = [mp.Source(mp.GaussianSource(frequency=fcen,fwidth=df),
                     component=mp.Hz,
                     center=mp.Vector3(Rb,0,0))]

vg = 0.23843879409589952 ## from MPB                                                                                                                                                                  
k = 1.51930003614631     ## from MPB                                                                                                                                                                  
m = 2*np.pi*k*Rb

sim = mp.Simulation(cell_size=cell_size,
                    resolution=resolution,
                    sources=sources,
                    boundary_layers=pml_layers,
                    dimensions=mp.CYLINDRICAL,
                    geometry=geometry,
                    m=m)

h = mp.Harminv(mp.Hz, mp.Vector3(Rb+0.019641,0,-0.5*sz+dpml+dsub+0.5*h+0.02895), fcen, df)
sim.run(mp.after_sources(h),
        until_after_sources=50)

for mode in h.modes:
    print("bending-loss:, {}, {}".format(1/mode.freq,mode.decay/(2*np.pi*vg)))
```

**Comment by stevengj** [comment]
A ridge waveguide might be better here, since that delocalizes the mode (in order to decrease scattering from sidewall roughness) and should greatly increase bending loss.

**Comment by stevengj** [comment]
Note that your results are inline with the [ring resonator tutorial] — with such a high index contrast, even with a 1λ diameter ring you already have Q on the order of ~1000.

PS. Note that `mode.decay/(2*np.pi*vg)))` looks like it should be `2*np.pi*mode.decay/vg`, since it is `mode.decay` that has an [implicit factor of 2π](https://github.com/NanoComp/meep/blob/03bf1cec666d6d39040c9120600d3bd1855fc12b/src/bands.cpp#L188).

**Comment by stevengj** [comment]
Note that you can call MPB through `get_eigenmode`.  (It might have a check that gives an error if it is in cylindrical coordinates?  But we could easily add a flag to ignore this and compute the mode as if it were Cartesian.)

**Comment by stevengj** [comment]
(Probably you don't need PML on the inner-r side, since all of the radiation losses should be in the outer direction.)

**Comment by oskooi** [comment]
It seems that it is not possible for `get_eigenmode` to accept a `where`/`eig_vol` argument in cylindrical coordinates and convert it to 2d cartesian for MPB.

Adding the following lines to the end of the script above:
```py
eig_data = sim.get_eigenmode(frequency=fcen,
                             direction=mp.Z,
                             where=mp.Volume(center=mp.Vector3(0.5*sr,0,0),size=mp.Vector3(sr,0,sz)),
                             band_num=1,
                             kpoint=mp.Vector3(0,0,1.5))
```
in which `where` defines the entire cell volume produces the error:
```
Traceback (most recent call last):
  File "waveguide_bending_loss.py", line 72, in <module>
    mp.Vector3(0,0,1.5))
  File "/usr/local/lib/python3.5/site-packages/meep/simulation.py", line 3433, in get_eigenmode
    match_frequency, parity, resolution, eigensolver_tol, kdom)
RuntimeError: meep: unsupported dimensionality in add_eigenmode_source
```
The cause of this error are these lines in the `get_eigenmode` definition:

https://github.com/NanoComp/meep/blob/03bf1cec666d6d39040c9120600d3bd1855fc12b/python/simulation.py#L3424-L3428

The function `_volume_from_kwargs` returns a `Volume` in cylindrical coordinates when passed a `where` object that is also in cylindrical coordinates. This redefined `where` object is then triggering an error when passed to `get_eigenmode`.

https://github.com/NanoComp/meep/blob/03bf1cec666d6d39040c9120600d3bd1855fc12b/python/simulation.py#L1263-L1277
