### ISSUE TITLE
Simulation fields are NaN or Inf in the adjoint solver

### ISSUE THREAD

**Issue by mawc2019** [NanoComp/meep#1676]
In the adjoint solver, the simulation sometimes stops in the adjoint run with the error message "RuntimeError: meep: simulation fields are NaN or Inf". I saw it happened in Near2FarFields and FourierFields, but I did not see it in EigenmodeCoefficient. An example for producing such an error in Near2FarFields is as follows, which resembles the [tutorial example](https://github.com/NanoComp/meep/blob/master/python/examples/adjoint_optimization/Near2Far-Optimization-with-Epigraph-Formulation.ipynb).

```
import meep as mp
import meep.adjoint as mpa
import numpy as np
from autograd import numpy as npa
Si = mp.Medium(index=3.4)
SiO2 = mp.Medium(index=1.44)

resolution = 30
design_region_resolution = resolution

design_region_width,design_region_height = 6,2
pml_size = 1.0
Sx,Sy = design_region_width,2*pml_size+design_region_height+5
cell_size = mp.Vector3(Sx,Sy)
pml_layers = [mp.PML(pml_size, direction=mp.Y)]

fcen,fwidth = 1/1.55,0.01/1.55
source_center,source_size  = mp.Vector3(0,-(design_region_height/2 + 1.5)),mp.Vector3(Sx,0)

src = mp.GaussianSource(frequency=fcen,fwidth=fwidth)
source = [mp.Source(src,component=mp.Ez,center=source_center,size=source_size)]
Nx,Ny = int(design_region_resolution*design_region_width),int(design_region_resolution*design_region_height)

design_variables = mp.MaterialGrid(mp.Vector3(Nx,Ny),SiO2,Si,grid_type='U_MEAN')
design_region = mpa.DesignRegion(design_variables,volume=mp.Volume(center=mp.Vector3(), size=mp.Vector3(design_region_width, design_region_height, 0)))

geometry = [mp.Block(center=design_region.center, size=design_region.size, material=design_variables)]

sim = mp.Simulation(
    cell_size=cell_size,boundary_layers=pml_layers,k_point=mp.Vector3(),geometry=geometry,
    sources=source,default_material=SiO2,resolution=resolution)

far_x = [mp.Vector3(0,40,0)]
NearRegions = [mp.Near2FarRegion(center=mp.Vector3(0,design_region_height/2+1.5), size=mp.Vector3(design_region_width+1.5,0), weight=+1)]
FarFields = mpa.Near2FarFields(sim, NearRegions,far_x)
ob_list = [FarFields]

def J(alpha):
    return npa.abs(alpha[0,0,2])**2

opt = mpa.OptimizationProblem(
    simulation = sim,objective_functions = J,objective_arguments = ob_list,design_regions = [design_region],
    fcen=fcen,df = 0,nf = 1,decay_by = 1e-5,decay_fields=[mp.Ez])

x0 = 0.5*np.ones(Nx*Ny)
opt.update_design([x0])
f0, g_adjoint = opt()
print("The value of the function is ",f0)
```

The error message is as follows.
```
Traceback (most recent call last):
  File "far_example_0713.py", line 79, in <module>
    f0, g_adjoint = opt()
  File "/home/gridsan/mawc/install/lib/python3.7/site-packages/meep/adjoint/optimization_problem.py", line 170, in __call__
    self.adjoint_run()
  File "/home/gridsan/mawc/install/lib/python3.7/site-packages/meep/adjoint/optimization_problem.py", line 318, in adjoint_run
    self.maximum_run_time,
  File "/home/gridsan/mawc/install/lib/python3.7/site-packages/meep/simulation.py", line 3646, in run
    self._run_sources_until(until_after_sources, step_funcs)
  File "/home/gridsan/mawc/install/lib/python3.7/site-packages/meep/simulation.py", line 2234, in _run_sources_until
    self._run_until(new_conds, step_funcs)
  File "/home/gridsan/mawc/install/lib/python3.7/site-packages/meep/simulation.py", line 2198, in _run_until
    self.fields.step()
  File "/home/gridsan/mawc/install/lib/python3.7/site-packages/meep/__init__.py", line 3736, in step
    return _meep.fields_step(self)
RuntimeError: meep: simulation fields are NaN or Inf
```
The monitor size is a little larger than the cell size in the x direction, where the periodic boundary condition is assumed. Although one can get rid of the error by shrinking the monitor to the same width as the cell, one can also easily get rid of the error by changing the resolution or sizes of geometric objects without shrinking the monitor to the same width as the cell.

**Comment by stevengj** [comment]
Thanks, I can reproduce this on my machine (running with a single processor).  Next I'll compile it with debugging turned on and see if I can reproduce; it's possible in principle to get the debugger to stop at the line where the NaN is created.

**Comment by stevengj** [comment]
The problem seems to be in the adjoint run…

**Comment by mawc2019** [comment]
Thanks! Yes, this error only happens in the adjoint run.
I am still searching for a simple case where the indeterminacy happens, because it may not be related to the above error. But at present I only see the indeterminacy in relatively complicated examples where optimization is performed and ``divide_parallel_processes`` is used.

**Comment by mawc2019** [comment]
Hi @smartalecH , this problem may also happen in the adjoint run of ``EigenmodeCoefficient``. An example is as follows.
```
import meep as mp
import meep.adjoint as mpa
import numpy as np
from autograd import numpy as npa

Si = mp.Medium(index=3.48)
SiO2 = mp.Medium(index=1.45)
Air = mp.Medium(index=1)

resolution,design_resolution = 20,20
design_region_width,design_region_height = 2,0.2
Lx,Ly = design_region_width,4
dpml = 1.5

monitor_height,monitor_width = design_region_height/2,0.1

pml_layers = [mp.PML(dpml, direction=mp.Y)]
cell_size = mp.Vector3(Lx,Ly+2*dpml)

fcen,fwidth = 1/1.55,0.01/1.55
k = mp.Vector3(fcen*1.45).rotate(mp.Vector3(z=1), np.pi/3)

source_center, source_size  = mp.Vector3(0,-Ly/4), mp.Vector3(Lx,0)
src = mp.GaussianSource(frequency=fcen,fwidth=fwidth)
source = [mp.EigenModeSource(src,eig_band = 1,direction=mp.NO_DIRECTION,eig_kpoint=k,size = source_size,center=source_center)]

Nx, Ny = int(round(design_resolution*design_region_width)), 1

design_variables = mp.MaterialGrid(mp.Vector3(Nx,Ny),Air,Si,grid_type='U_MEAN')
design_region = mpa.DesignRegion(design_variables,volume=mp.Volume(center=mp.Vector3(0,design_region_height/2),size=mp.Vector3(design_region_width,design_region_height)))

geometry = [mp.Block(center=mp.Vector3(0,-Ly/4-dpml/2), material=SiO2, size=mp.Vector3(Lx,Ly/2+dpml, 0)), # subtrate
    mp.Block(center=design_region.center, size=design_region.size, material=design_variables) # design region
]

sim = mp.Simulation(
    cell_size=cell_size,boundary_layers=pml_layers,geometry=geometry,sources=source,k_point=k,eps_averaging=False,resolution=resolution)
TE0 = mpa.EigenmodeCoefficient(sim,mp.Volume(center=mp.Vector3(0,monitor_height),size=mp.Vector3(monitor_width,0)),mode=1)
ob_list = [TE0]

def J(alpha):
    return npa.abs(alpha)**2

opt = mpa.OptimizationProblem(
    simulation = sim,objective_functions = J,objective_arguments = ob_list,design_regions = [design_region],
    fcen=fcen,df = 0,nf = 1,decay_by = 1e-5,decay_fields=[mp.Ez])

x0 = 0.5*np.ones(Nx*Ny)
opt.update_design([x0])
f0, dJ_deps = opt()
```

If ``monitor_width`` is changed from 0.1 to some other values, such as 0.09 or 0.11, ``RuntimeError: meep: simulation fields are NaN or Inf`` does not appear.

**Comment by mawc2019** [comment]
The `nan` simulation results similar to the case in the forward run above can be illustrated without the adjoint solver. An example is as follows. No error is reported although the result is an array filled with `nan+nanj`.

```
import meep as mp
import numpy as np

resolution = 20
Lx,Ly = 2,4
dpml = 1.5

monitor_height,monitor_width = 0.1,0.1

pml_layers = [mp.PML(dpml, direction=mp.Y)]
cell_size = mp.Vector3(Lx,Ly+2*dpml)

fcen,fwidth = 1/1.55,0.01/1.55
k = mp.Vector3(fcen).rotate(mp.Vector3(z=1), np.pi/3)

source_center, source_size  = mp.Vector3(0,-Ly/4), mp.Vector3(Lx,0)
src = mp.GaussianSource(frequency=fcen,fwidth=fwidth)
source = [mp.EigenModeSource(src,eig_band = 1,direction=mp.NO_DIRECTION,eig_kpoint=k,size = source_size,center=source_center)]

geometry = [mp.Block(center=mp.Vector3(0,-Ly/4-dpml/2), material=mp.Medium(index=1), size=mp.Vector3(Lx,Ly/2+dpml, 0))]

sim = mp.Simulation(
    cell_size=cell_size,boundary_layers=pml_layers,geometry=geometry,sources=source,k_point=k,eps_averaging=False,resolution=resolution)
mode_monitor = sim.add_mode_monitor(fcen,0,1,mp.ModeRegion(center=mp.Vector3(0,monitor_height),size=mp.Vector3(monitor_width,0)),yee_grid=True)

sim.run(until_after_sources=100)

emc = sim.get_eigenmode_coefficients(mode_monitor, [1], direction=mp.AUTOMATIC)[0]
print("emc = ", emc.flatten())
```

**Comment by smartalecH** [comment]
Your mode monitor spans a really small volume in air:

```
mode_monitor = sim.add_mode_monitor(fcen,0,1,mp.ModeRegion(center=mp.Vector3(0,monitor_height),size=mp.Vector3(Lx,0)),yee_grid=True)
```

It's calculating a weird mode that's having trouble with the overlap integral. If you make it bigger (e.g. the width of the cell) then you get an actual number.

```
emc =  [ 2.69954684e-05-4.19713973e-05j -3.52574306e-07+6.38456848e-07j]
```

**Comment by mawc2019** [comment]
> Your mode monitor spans a really small volume in air

We may get actual numbers when `monitor_width` takes smaller values, e.g., 0.09, 0.01, and so on. (In the above example that shows `nan`, there is `monitor_width=0.1`.)

> If you make it bigger (e.g. the width of the cell) then you get an actual number.

When I set `monitor_width=0.7000000000000001`, the result is still `nan`.

**Comment by smartalecH** [comment]
@mawc2019 is this still an issue?

**Comment by mawc2019** [comment]
I am recently mainly using the latest released version, namely, [v1.23.0](https://github.com/NanoComp/meep/tree/v1.23.0). The error `NaN or Inf` appears occasionally, which is difficult to reproduce because the results in different runs are slightly different. When I encountered `NaN or Inf` and ran the same code again, this error disappeared.
