### ISSUE TITLE
add epsilon colorbar for plot2D

### ISSUE THREAD

**Issue by joamatab** [NanoComp/meep#2286]
How could we add an epislon or refractive index colorbar for plot2D? 

See for example the colorbars here
https://gdsfactory.github.io/gdsfactory/notebooks/plugins/tidy3d/00_tidy3d.html

Also we could improve Meeps' 3D visualization using trimesh?

https://gdsfactory.github.io/gdsfactory/notebooks/plugins/meep/001_meep_sparameters.html#Visualizing-the-3D-Geometry

**Comment by SkandanC** [comment]
Meep's current plot3D() function is broken, due to issues with mayavi. 

```
Traceback (most recent call last):
  File "/home/skandanc/plot.py", line 14, in <module>
    sim.plot3D()
  File "/home/skandanc/miniconda3/lib/python3.9/site-packages/meep/simulation.py", line 4213, in plot3D
    return vis.plot3D(self)
  File "/home/skandanc/miniconda3/lib/python3.9/site-packages/meep/visualization.py", line 681, in plot3D
    from mayavi import mlab
  File "/home/skandanc/miniconda3/lib/python3.9/site-packages/mayavi/mlab.py", line 34, in <module>
    from .tools.helper_functions import contour3d, test_contour3d, \
  File "/home/skandanc/miniconda3/lib/python3.9/site-packages/mayavi/tools/helper_functions.py", line 16, in <module>
    from .modules import VectorsFactory, StreamlineFactory, GlyphFactory, \
  File "/home/skandanc/miniconda3/lib/python3.9/site-packages/mayavi/tools/modules.py", line 27, in <module>
    from .filters import new_class
  File "/home/skandanc/miniconda3/lib/python3.9/site-packages/mayavi/tools/filters.py", line 232, in <module>
    _make_functions(locals())
  File "/home/skandanc/miniconda3/lib/python3.9/site-packages/mayavi/tools/filters.py", line 218, in _make_functions
    klass = new_class(
  File "/home/skandanc/miniconda3/lib/python3.9/site-packages/mayavi/tools/filters.py", line 30, in new_class
    return new.classobj(name, bases, dict_)
AttributeError: module 'new' has no attribute 'classobj'
```

I managed to create a rudimentary 3D representation of the Simulation object using vispy. I need to add the source planes and monitor planes, and fine tune the looks. Sim object for an MMI1X2:

![image](https://user-images.githubusercontent.com/100642027/198529973-d83bd96f-198b-4466-9b15-7ae9b57634d5.png)

**Comment by thomasdorch** [comment]
How about using [pyvista](https://github.com/pyvista/pyvista) for 3D plotting? I don't have much experience with it but it looks like it has support for opacity, plus it can import hdf files so it would integrate well.

Also I just put in a PR (#2289) for the colorbars so let me know how that works for you!

**Comment by SkandanC** [comment]
![image](https://user-images.githubusercontent.com/100642027/198856593-84c02ff3-de15-49e4-b079-ee79255514ba.png)
Final version. The function can now also plot structures with different eps, each of which is given a different shade of grey. We can adopt @thomasdorch's new colorbar and add it to this scene as well.

**Comment by smartalecH** [comment]
> Final version. The function can now also plot structures with different eps

@SkandanC hey, this is pretty cool!

**Comment by SkandanC** [comment]
Thank you! I think this could be useful to visualize the adjoint optimization simulation objects as well.

**Comment by SkandanC** [comment]
@joamatab do you think this should be closed? Both the colorbars and 3d visualization PRs have been merged.
