### ISSUE TITLE
Conda missing scipy dependency

### ISSUE THREAD

**Issue by SirNate0** [NanoComp/meep#2658]
Installing parallel meep as suggested in the documentation,
```sh
conda create -n pmp -c conda-forge pymeep=*=mpi_mpich_*
```
there seems to be a missing dependency on scipy. When I `import meep`, I get
```
Traceback (most recent call last):                                                                                  
  File "<stdin>", line 1, in <module>                                                                               
  File "/home/nathan/Tools/miniconda/envs/pmp/lib/python3.11/site-packages/meep/__init__.py", line 4250, in <module>
    from .simulation import (                                                                                       
  File "/home/nathan/Tools/miniconda/envs/pmp/lib/python3.11/site-packages/meep/simulation.py", line 12, in <module>
    from scipy.interpolate import pade                                                                              
ModuleNotFoundError: No module named 'scipy' 
```

**Comment by SirNate0** [comment]
My issue with the current arrangement is that scipy/matplotlib are required just to `import meep`, and not only to run the tutorials. I.e. the meep package depends on them, but conda is not aware of this. At the very least, maybe add the `pymeep-extras` package to the suggested command for installing parallel meep? 

A better option would probably be to make it so that meep can be imported without the dependencies. Particularly matplotlib, a large dependency which seems to only be needed to use Axes in a type annotation [here](https://github.com/NanoComp/meep/blob/ae9cb64e9e9d2237b5473c048518266c82ce387f/python/simulation.py#L4744) ([which seems to be possible without importing the class](https://www.reddit.com/r/learnpython/comments/r98a4m/type_hinting_without_importing_desired_class/))

**Comment by oskooi** [comment]
scipy is a required dependency to enable the `PadeApproximant` feature which was recently added in #2440.

matplotlib is required for the visualization routines including [`plot2D`](https://meep.readthedocs.io/en/latest/Python_User_Interface/#data-visualization). The documentation for this routine does state "Requires matplotlib." 

It would be possible to import the Meep module without scipy and matplotlib but this would require some changes to the code. For now, we can simply make it clear in the installation page that installing the additional package `pymeep-extras` is recommended.

**Comment by stevengj** [comment]
The point is that the conda package for meep should list these dependencies, so that they get automatically installed.

**Comment by oskooi** [comment]
> The point is that the conda package for meep should list these dependencies, so that they get automatically installed.

The `pymeep` Conda package now includes matplotlib and scipy (conda-forge/pymeep-feedstock#79). 

(It will take a few hours for Conda forge to update this [package](https://anaconda.org/conda-forge/pymeep).)
