### ISSUE TITLE
failing get_farfield test due to multithreading

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#878]
Following the recent addition of multithreading support for `get_farfields` (#868), `python/tests/cavity_farfield.py` of the `make check` suite fails when built using `--with-openmp` (as well as `--with-mpi`). The output log is:

```
Using MPI version 3.0, 2 processes
-----------
Initializing structure...
Halving computational cell along direction x
Halving computational cell along direction y
Working in 2D dimensions.
Computational cell is 12.4 x 6 x 0 with resolution 10
     block, center = (0,0,0)
          size (1e+20,1.2,1e+20)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (13,13,13)
     cylinder, center = (0.7,0,0)
          radius 0.36, height 1e+20, axis (0, 0, 1)
          dielectric constant epsilon diagonal = (1,1,1)
     cylinder, center = (-0.7,0,0)
          radius 0.36, height 1e+20, axis (0, 0, 1)
          dielectric constant epsilon diagonal = (1,1,1)
     cylinder, center = (1.7,0,0)
          radius 0.36, height 1e+20, axis (0, 0, 1)
          dielectric constant epsilon diagonal = (1,1,1)
     cylinder, center = (-1.7,0,0)
          radius 0.36, height 1e+20, axis (0, 0, 1)
          dielectric constant epsilon diagonal = (1,1,1)
     cylinder, center = (2.7,0,0)
          radius 0.36, height 1e+20, axis (0, 0, 1)
          dielectric constant epsilon diagonal = (1,1,1)
     cylinder, center = (-2.7,0,0)
          radius 0.36, height 1e+20, axis (0, 0, 1)
          dielectric constant epsilon diagonal = (1,1,1)
time for set_epsilon = 0.00404215 s
-----------
run 0 finished at t = 200.0 (4000 timesteps)
..-----------
Initializing structure...
Halving computational cell along direction x
Halving computational cell along direction y
Working in 2D dimensions.
Computational cell is 12.4 x 6 x 0 with resolution 10
     block, center = (0,0,0)
          size (1e+20,1.2,1e+20)
          axes (1,0,0), (0,1,0), (0,0,1)
          dielectric constant epsilon diagonal = (13,13,13)
     cylinder, center = (0.7,0,0)
          radius 0.36, height 1e+20, axis (0, 0, 1)
          dielectric constant epsilon diagonal = (1,1,1)
     cylinder, center = (-0.7,0,0)
          radius 0.36, height 1e+20, axis (0, 0, 1)
          dielectric constant epsilon diagonal = (1,1,1)
     cylinder, center = (1.7,0,0)
          radius 0.36, height 1e+20, axis (0, 0, 1)
          dielectric constant epsilon diagonal = (1,1,1)
     cylinder, center = (-1.7,0,0)
          radius 0.36, height 1e+20, axis (0, 0, 1)
          dielectric constant epsilon diagonal = (1,1,1)
     cylinder, center = (2.7,0,0)
          radius 0.36, height 1e+20, axis (0, 0, 1)
          dielectric constant epsilon diagonal = (1,1,1)
     cylinder, center = (-2.7,0,0)
          radius 0.36, height 1e+20, axis (0, 0, 1)
          dielectric constant epsilon diagonal = (1,1,1)
time for set_epsilon = 0.00350618 s
-----------
run 0 finished at t = 200.0 (4000 timesteps)
FF
======================================================================
FAIL: test_cavity_farfield_four_freqs (__main__.TestCavityFarfield)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/cavity_farfield.py", line 85, in test_cavity_farfield_four_freqs
    self.run_test(nfreqs=4)
  File "./tests/cavity_farfield.py", line 74, in run_test
    np.testing.assert_allclose(ref_ex, result['Ex'])
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 1391, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 733, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 3.9663461538461604%)
 x: array([[[ 0.014870-0.144274j,  0.014870-0.144274j,  0.014870-0.144274j,
          0.014870-0.144274j],
        [ 0.037215-0.139958j,  0.037215-0.139958j,  0.037215-0.139958j,...
 y: array([[[ 0.014870-0.144274j,  0.014870-0.144274j,  0.014870-0.144274j,
          0.014870-0.144274j],
        [ 0.037215-0.139958j,  0.037215-0.139958j,  0.037215-0.139958j,...

----------------------------------------------------------------------
Ran 2 tests in 6.350s

FAILED (failures=1)

======================================================================
FAIL: test_cavity_farfield_four_freqs (__main__.TestCavityFarfield)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/cavity_farfield.py", line 85, in test_cavity_farfield_four_freqs
    self.run_test(nfreqs=4)
  File "./tests/cavity_farfield.py", line 74, in run_test
    np.testing.assert_allclose(ref_ex, result['Ex'])
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 1391, in assert_allclose
    verbose=verbose, header=header)
  File "/usr/lib/python3/dist-packages/numpy/testing/utils.py", line 733, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 3.9663461538461604%)
 x: array([[[ 0.014870-0.144274j,  0.014870-0.144274j,  0.014870-0.144274j,
          0.014870-0.144274j],
        [ 0.037215-0.139958j,  0.037215-0.139958j,  0.037215-0.139958j,...
 y: array([[[ 0.014870-0.144274j,  0.014870-0.144274j,  0.014870-0.144274j,
          0.014870-0.144274j],
        [ 0.037215-0.139958j,  0.037215-0.139958j,  0.037215-0.139958j,...

----------------------------------------------------------------------
Ran 2 tests in 6.349s

FAILED (failures=1)

Elapsed run time = 6.3582 s

Field time usage:
        connecting chunks: 0.0031209 s
            time stepping: 0.223366 s
            communicating: 0.107471 s
     Fourier transforming: 0.0369229 s
        getting farfields: 1.65794 s
          everything else: 0.0598614 s


Field time usage:
        connecting chunks: 0.00287127 s
            time stepping: 0.224716 s
            communicating: 0.107758 s
     Fourier transforming: 0.0530689 s
        getting farfields: 3.68388 s
          everything else: 0.0571985 s

-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[25678,1],0]
  Exit code:    1
--------------------------------------------------------------------------
FAIL tests/cavity_farfield.py (exit status: 1)
```
There are two possible fixes: (1) update the hard-coded reference values in `python/tests/data/cavity-farfield.h5`, or (2) lower the tolerance `rtol`  value (default: `1e-7`) in the [`assert_allclose`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.testing.assert_allclose.html) comparison.

**Comment by ChristopherHogan** [comment]
A few observations:

```
# compiled with -O2 (default)
$ OMP_NUM_THREADS=2 mpirun -n 2 python cavity_farfields.py
FAIL

$ OMP_NUM_THREADS=2 python cavity_farfields.py
FAIL

$ OMP_NUM_THREADS=1 mpirun -n 2 python cavity_farfields.py
PASS

# compiled with -O0
$ OMP_NUM_THREADS=2 mpirun -n 2 python cavity_farfields.py
PASS
```

**Comment by stevengj** [comment]
`3.9%` is a surprisingly big difference here — which are the specific values in `x` and `y` that are different?

It is also surprising at first glance that we see any difference, since OpenMP only parallelizes over frequencies—that is, each frequency is evaluated just as in the serial code—and and the different frequencies in the tests are never combined, correct?

**Comment by ChristopherHogan** [comment]
FYI, I'm seeing anywhere between a 30% and 90% mismatch:
```
Mismatch: 90.6%
Max absolute difference: 0.07880852
Max relative difference: 0.90547838
 x: array([[[ 0.01487 -0.144274j,  0.01487 -0.144274j,  0.01487 -0.144274j,
          0.01487 -0.144274j],
        [ 0.037215-0.139958j,  0.037215-0.139958j,  0.037215-0.139958j,...
 y: array([[[ 7.407395e-03-0.119801j,  1.770778e-02-0.16892j ,
          5.851198e-03-0.140526j,  2.132121e-02-0.151424j],
        [ 4.808763e-02-0.087053j,  2.516004e-02-0.159496j,...

```
Although it works fine without optimizations (`-O0`).

**Comment by stevengj** [comment]
I just noticed that the `EH6` variable was not used in thread-safe way, fixed by bb978fb597240659693039fa0ede2e868094e429 … try it again?

**Comment by ChristopherHogan** [comment]
It's working now. That seems to have fixed it.

**Comment by oskooi** [comment]
The test is passing now. However, when running `make check`, OpenMP's default behavior is to use *all* available cores which unfortunately slows down the `get_farfield` tests `cavity_farfield.py` and `antenna_radiation.py` by a factor of >5X (on a machine with 8 cores/threads) compared to a single thread. Since the default for `--with-mpi` is to use 2 processes during `make check`, it might be useful to also define `OMP_NUM_THREADS=2` for `--with-openmp` to ensure reasonable throughput.
