### ISSUE TITLE
plot2D with complex fields

### ISSUE THREAD

**Issue by oskooi** [NanoComp/meep#934]
The `plot2D` routine of the [visualization module](https://meep.readthedocs.io/en/latest/Python_User_Interface/#data-visualization) does not seem to work for complex fields. This is demonstrated in the following example which is based on [Python Tutorials/Eigenmode Source/Planewaves in Homogeneous Media](https://meep.readthedocs.io/en/latest/Python_Tutorials/Eigenmode_Source/#planewaves-in-homogeneous-media).
```py
import meep as mp
import numpy as np
import matplotlib.pyplot as plt

resolution = 50  # pixels/μm                                                                                                                                                  

cell_size = mp.Vector3(14,10,0)

pml_layers = [mp.PML(thickness=2,direction=mp.X)]

# rotation angle (in degrees) of planewave, counter clockwise (CCW) around z-axis                                                                                             
rot_angle = np.radians(20)

fsrc = 1.0  # frequency of planewave (wavelength = 1/fsrc)                                                                                                                    

n = 1.5  # refractive index of homogeneous material                                                                                                                           
default_material = mp.Medium(index=n)

k_point = mp.Vector3(fsrc*n).rotate(mp.Vector3(z=1), rot_angle)

sources = [mp.EigenModeSource(src=mp.ContinuousSource(fsrc),
                              center=mp.Vector3(),
                              size=mp.Vector3(y=10),
                              direction=mp.AUTOMATIC if rot_angle == 0 else mp.NO_DIRECTION,
                              eig_kpoint=k_point,
                              eig_band=1,
                              eig_parity=mp.EVEN_Y+mp.ODD_Z if rot_angle == 0 else mp.ODD_Z,
                              eig_match_freq=True)]

sim = mp.Simulation(cell_size=cell_size,
                    resolution=resolution,
                    boundary_layers=pml_layers,
                    sources=sources,
                    k_point=k_point,
                    default_material=default_material,
                    symmetries=[mp.Mirror(mp.Y)] if rot_angle == 0 else [])

sim.run(until=100)

sim.plot2D(output_plane=mp.Volume(center=mp.Vector3(), size=mp.Vector3(10,10,0)),
           fields=mp.Ez,
           field_parameters={'interpolation':'spline36', 'cmap':'RdBu'})

plt.show()
```
Due to the non-zero `k_point`, the fields are complex. Since the `plot2D` interface does not currently provide the capability to choose which of the real or imaginary part of the specified field component to use, the script aborts with the following error:
```
run 0 finished at t = 100.0 (10000 timesteps)
Traceback (most recent call last):
  File "oblique-planewave.py", line 52, in <module>
    field_parameters={'interpolation':'spline36', 'cmap':'RdBu'})
  File "/usr/local/lib/python3.5/site-packages/meep/simulation.py", line 2220, in plot2D
    return vis.plot2D(self,**kwargs)
  File "/usr/local/lib/python3.5/site-packages/meep/visualization.py", line 523, in plot2D
    ax = plot_fields(sim,ax,fields,output_plane=output_plane,field_parameters=field_parameters)
  File "/usr/local/lib/python3.5/site-packages/meep/visualization.py", line 486, in plot_fields
    ax.imshow(np.rot90(fields), extent=extent, **field_parameters)
  File "/home/oskooi/.local/lib/python3.5/site-packages/matplotlib/__init__.py", line 1810, in inner
    return func(ax, *args, **kwargs)
  File "/home/oskooi/.local/lib/python3.5/site-packages/matplotlib/axes/_axes.py", line 5494, in imshow
    im.set_data(X)
  File "/home/oskooi/.local/lib/python3.5/site-packages/matplotlib/image.py", line 634, in set_data
    raise TypeError("Image data cannot be converted to float")
TypeError: Image data cannot be converted to float

Elapsed run time = 33.4651 s
```
*Solution*: add an extra option i.e. `real_imag` to `field_parameters` which can be set to either `r` or `i` (`r` by default). The same option should be added to `source_parameters` since its amplitude can also be complex (e.g., planewave).

**Comment by stevengj** [comment]
Maybe have `imag=False` as a parameter, so that if you pass `imag=True` it plots the imaginary part.
