### ISSUE TITLE
__swig_getmethods__ no longer exists in SWIG 4.0.0?

### ISSUE THREAD

**Issue by stevengj** [NanoComp/meep#965]
I am getting
```
>>> import meep
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/stevenj/Local/lib/python2.7/site-packages/meep/__init__.py", line 2631, in <module>
    class dft_ldos(object):
  File "/Users/stevenj/Local/lib/python2.7/site-packages/meep/__init__.py", line 2670, in dft_ldos
    __swig_getmethods__["freq_min"] = get_omega_min
NameError: name '__swig_getmethods__' is not defined
```
This is due to a call to the internal function `__swig_getmethods__` in `python/meep.i` introduced by #581.   It looks like this no longer exists?

**Comment by stevengj** [comment]
If I comment out the `__swig_getmethods__` calls, I also get an error on `_newclass`:
```
>>> import meep
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/stevenj/Local/lib/python2.7/site-packages/meep/__init__.py", line 2631, in <module>
    class dft_ldos(object):
  File "/Users/stevenj/Local/lib/python2.7/site-packages/meep/__init__.py", line 2673, in dft_ldos
    if _newclass: freq_min = property(get_omega_min)
NameError: name '_newclass' is not defined
```

**Comment by sh-zam** [comment]
Yes, apparently. It also broke lldb scripting.

**Comment by stevengj** [comment]
Right now as a stopgap I'm just manually commenting out the `__swig_getmethods__` and `_newclass` calls, which only affect the `dft_ldos` feature.

**Comment by oskooi** [comment]
While #1154 removes the `__swig_getmethods__` calls introduced in #581, building the master branch with SWIG 4.0.1 (by disabling [these lines](https://github.com/NanoComp/meep/blob/master/configure.ac#L523-L527) in `configure.ac`) on Ubuntu produces the following error in `python/tests/simulation.py`:

```
======================================================================
ERROR: test_vec_constructor (__main__.TestSimulation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/install/meep/python/meep/simulation.py", line 57, in vec
    return mp._vec(*args)
  File "/home/ubuntu/install/meep/python/meep/__init__.py", line 1050, in _vec
    val = _meep.new__vec(*args)
TypeError: Wrong number or type of arguments for overloaded function 'new__vec'.
  Possible C/C++ prototypes are:
    meep::vec::vec()
    meep::vec::vec(double)
    meep::vec::vec(double,double)
    meep::vec::vec(double,double,double)
```
All other C/Python tests pass, however.
